const router = require('express').Router();
const publicBlogController = require('../controllers/public/blogController');

router.use('/auth', require('./user/userAuthRoutes'));
router.use('/users/auth', require('./user/userAuthRoutes'));
router.use('/users/profile', require('./user/userProfileRoutes'));
router.use('/users/notifications', require('./user/userNotificationRoutes'));
router.use('/users/wallet', require('./user/userWalletRoutes'));
router.use('/users/payments', require('./user/userPaymentRoutes'));
router.use('/users/coupons', require('./user/userCouponRoutes'));
router.use('/users/referrals', require('./user/userReferralRoutes'));
router.use('/users/horoscopes', require('./user/userHoroscopeRoutes'));
router.use('/users/chat', require('./user/userChatRoutes'));
router.use('/content', require('./contentRoutes'));
router.use('/', require('./bookingRoutes'));
router.use('/paypal', require('./payment/paypalRoutes'));
router.use('/blogs', require('./blogRoutes'));

router.get('/public/blogs', publicBlogController.listBlogs);
router.get('/public/blogs/categories', publicBlogController.listCategories);
router.get('/public/blogs/featured', publicBlogController.listFeaturedBlogs);
router.get('/public/blogs/:id/related', publicBlogController.getRelatedBlogsById);
router.post('/public/blogs/:id/view', publicBlogController.incrementViewCount);
router.get('/public/blogs/:slug', publicBlogController.getBlogBySlug);
router.get('/public/blog-categories', publicBlogController.listCategories);

router.use('/admin/auth', require('./admin/adminAuthRoutes'));
router.use('/admin/profile', require('./admin/adminProfileRoutes'));
router.use('/admin/users', require('./admin/adminUserRoutes'));
router.use('/admin/users', require('./admin/adminUserCreditsRoutes'));
router.use('/admin/chat-access-requests', require('./admin/adminChatAccessRoutes'));
router.use('/admin/chat-requests', require('./admin/adminChatAccessRoutes'));
router.use('/admin/chat', require('./admin/adminChatRoutes'));
router.use('/admin/referrals', require('./admin/adminReferralRoutes'));
router.use('/admin/payments', require('./admin/adminPaymentRoutes'));
router.use('/admin/blogs', require('./adminBlogRoutes'));
router.use('/admin/blog-categories', require('./adminBlogCategoryRoutes'));
router.use('/admin/coupons', require('./admin/adminCouponRoutes'));
router.use('/admin/bonuses', require('./admin/adminBonusRoutes'));
router.use('/admin/pricing', require('./admin/adminPricingRoutes'));
router.use('/admin/notifications', require('./admin/adminNotificationRoutes'));
router.use('/admin/horoscopes', require('./admin/adminHoroscopeRoutes'));
router.use('/admin/rashis', require('./admin/adminRashiRoutes'));
router.use('/admin/banners', require('./admin/adminBannerRoutes'));
router.use('/admin/refunds', require('./admin/adminRefundRoutes'));
router.use('/admin/invoices', require('./admin/adminInvoiceRoutes'));
router.use('/admin/recharge-plans', require('./admin/adminRechargePlanRoutes'));
router.use('/admin/analytics', require('./admin/adminAnalyticsRoutes'));
router.use('/admin/page-content', require('./admin/adminPageContentRoutes'));
router.use('/admin/pageContent', require('./admin/adminPageContentRoutes'));
router.use('/admin/content/pages', require('./admin/adminPageContentRoutes'));
router.use('/admin/content/page-content', require('./admin/adminPageContentRoutes'));
router.use('/admin/close-requests', require('./admin/adminCloseRequestRoutes'));
router.use('/admin/closeRequests', require('./admin/adminCloseRequestRoutes'));
router.use('/admin/drop-messages', require('./admin/adminDropMessageRoutes'));
router.use('/admin/dropMessages', require('./admin/adminDropMessageRoutes'));
router.use('/admin/mailer', require('./admin/adminEmailRoutes'));
router.use('/admin/email', require('./admin/adminEmailRoutes'));
router.use('/admin/emails', require('./admin/adminEmailRoutes'));
router.use('/admin/newsletter', require('./admin/adminEmailRoutes'));
router.use('/admin/newsletters', require('./admin/adminEmailRoutes'));
router.use('/admin/send-email', require('./admin/adminEmailRoutes'));
router.use('/admin/send-bulk-email', require('./admin/adminEmailRoutes'));
router.use('/admin/bulk-email', require('./admin/adminEmailRoutes'));
router.use('/admin/bulk-emails', require('./admin/adminEmailRoutes'));

router.use('/admin/dashboard', require('./admin/adminDashboardRoutes'));
router.use('/admin/subscribers', require('./admin/adminSubscribersRoutes'));
router.use('/admin/user-credits', require('./admin/adminUserCreditsRoutes'));
router.use('/admin/refund-transactions', require('./admin/adminRefundTransactionsRoutes'));
router.use('/admin/refund-amounts', require('./admin/adminRefundAmountsRoutes'));
router.use('/admin/history-notes', require('./admin/adminHistoryNotesRoutes'));

module.exports = router;
